<?php
/**
 * 活动实体类
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.23
 * Time: 15:23
 */

namespace app\admin\model;


use think\Model;

class Active extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}