<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.24
 * Time: 14:17
 */

namespace app\admin\model;


use think\Model;

class CouponCat extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}