<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.23
 * Time: 16:53
 */

namespace app\admin\model;


use think\Model;

class Coupon extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}