<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.4.21
 * Time: 16:13
 */

namespace app\admin\controller;


class Marketing extends BaseController
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 积分设置
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function scoreSet()
    {
        $scoreModel = model('ScoreSet', 'model');
        $data = $scoreModel->find();
        if (request()->isAjax()) {
            if ($data) {
                if ($scoreModel->allowField(true)->save($_POST, '1=1')) {
                    exit_json();
                } else {
                    exit_json(-1, '操作失败');
                }
            }
            if ($scoreModel->allowField(true)->save($_POST)) {
                exit_json();
            } else {
                exit_json(-1, '操作失败');
            }
        } else {
            $data = $scoreModel->find();
            $this->assign('data', $data);
            return $this->fetch();
        }
    }

    /**
     * 活动列表
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function active()
    {
        $actives = db('active')->select();
        $this->assign('actives', $actives);
        return $this->fetch();
    }

    /**
     * 添加活动
     */
    public function active_add()
    {
        if (request()->isAjax()) {
            $data = input('post.');
            $res = model('active')->allowField(true)->save($data);
            if ($res) {
                exit_json();
            } else {
                exit_json(-1, '添加活动失败');
            }
        } else {
            return $this->fetch();
        }
    }

    /**
     * 编辑活动
     */
    public function active_edit()
    {
        if (request()->isAjax()) {
            $data = input('post.');
            $res = model('active')->allowField(true)->save($data, ['id' => $data['id']]);
            if ($res) {
                exit_json();
            } else {
                exit_json(-1, '编辑活动失败');
            }
        } else {
            $active = model('active')->where('id', input('id'))->find();
            $this->assign('active', $active);
            return $this->fetch();
        }
    }

    /**
     * 删除活动
     */
    public function active_del()
    {
        $id = input('id');
        $res = model('active')->where('id', $id)->delete();
        if ($res) {
            exit_json();
        } else {
            exit_json(-1, '删除失败');
        }

    }

    /**
     * 更改活动状态
     */
    public function changeStatus()
    {
        $id = input('id');
        $status = input('status');
        $res = model('active')->save(['is_open' => $status], ['id' => $id]);
        if ($res) {
            exit_json();
        } else {
            exit_json(-1, '删除失败');
        }
    }

    /**
     * 优惠券分类列表
     */
    public function coupon_cat()
    {
        $list = model('CouponCat')->select();
        $this->assign('list', $list);
        return $this->fetch();
    }

    /**
     * 添加优惠券类型
     */
    public function coupon_cat_add()
    {
        if (request()->isAjax()) {
            $cat_name = input('cat_name');
            if ($cat_name) {
                $res = model('coupon_cat')->save(['cat_name' => $cat_name]);
                if ($res) {
                    exit_json();
                }
            }
            exit_json(-1, '参数错误');
        } else {
            return $this->fetch();
        }
    }

    /**
     * 编辑优惠券类型
     */
    public function coupon_cat_edit()
    {
        if (request()->isAjax()) {
            $cat_name = input('cat_name');
            if ($cat_name) {
                $res = model('coupon_cat')->save(['cat_name' => $cat_name], ['id' => input('id')]);
                if ($res) {
                    exit_json();
                }
            }
            exit_json(-1, '参数错误');
        } else {
            $cat_id = input('cat_id');
            $cat = model('coupon_cat')->where('id', $cat_id)->find();
            $this->assign('cat', $cat);
            return $this->fetch();
        }
    }

    /**
     * 删除
     */
    public function coupon_cat_del()
    {
        $cat_id = input('id');
        if ($cat_id) {
            $res = model('coupon_cat')->where('id', $cat_id)->delete();
            if ($res) {
                exit_json();
            } else {
                exit_json(-1, '参数错误');
            }
        } else {
            exit_json(-1, '参数错误');
        }

    }

    /**
     * 优惠券列表
     */
    public function coupon()
    {
        $couponList = model('coupon')->select();
        $coupon_cat = model('coupon_cat')->column('cat_name', 'id');
        $this->assign('cat', $coupon_cat);
        $this->assign('list', $couponList);
        return $this->fetch();
    }

    /**
     * 添加优惠券
     */
    public function coupon_add()
    {
        if (request()->isAjax()) {
            $data = input('post.');
            $res = model('coupon')->allowField(true)->save($data);
            if ($res) {
                exit_json();
            } else {
                exit_json(-1, '添加失败');
            }
        } else {
            $coupon_cat = model('coupon_cat')->select();
            $this->assign('coupon_cat', $coupon_cat);
            return $this->fetch();
        }

    }

    /**
     * 编辑优惠券
     */
    public function coupon_edit()
    {
        if (request()->isAjax()) {
            $data = input('post.');
            $res = model('coupon')->where($data)->find();
            if ($res) {
                exit_json();
            } else {
                $res = model('coupon')->allowField(true)->save($data, ['id' => $data['id']]);
                if ($res) {
                    exit_json();
                }
                exit_json(-1, '添加失败');
            }
        } else {
            $coupon_id = input('id');
            $data = model('coupon')->where('id', $coupon_id)->find();
            $this->assign('data', $data);
            $coupon_cat = model('coupon_cat')->select();
            $this->assign('coupon_cat', $coupon_cat);
            return $this->fetch();
        }

    }

    /**
     * 会员充值
     */
    public function charge()
    {
        $charge_list = model('ChargeAct')->select();
        $this->assign('list', $charge_list);
        return $this->fetch();
    }

    /**
     * 充值活动添加
     */
    public function charge_add()
    {
        if(request()->isAjax()){
            $data = input('post.');
            $res = model('charge_act')->save($data);
            if($res){
                exit_json();
            }else{
                exit_json(-1, '添加失败');
            }
        }
        return $this->fetch();
    }

    /**
     * 充值活动编辑
     */
    public function charge_edit()
    {
        $cid = input('id');
        $charge = model('charge_act')->where('id', $cid)->find();
        if(request()->isAjax()){
            $money = input('money');
            $given_money = input('given_money');
            model('charge_act')->save(['money'=>$money, 'given_money'=>$given_money], ['id'=>$cid]);
            exit_json();
        }
        $this->assign('item', $charge);
        return $this->fetch();

    }

    /**
     * 更改活动类型
     */
    public function chargeStatus()
    {
        $c_id = input('id');
        $status = input('status');
        $res = model('charge_act')->save(['status' => $status], ['id' => $c_id]);
        if ($res) {
            exit_json(1, '请求成功');
        } else {
            exit_json(-1, '更改失败');
        }
    }

    /**
     * 加盟我们
     */
    public function join_us()
    {
        $list = model('join_us')->order('status, create_time desc')->select();
        $this->assign('list', $list);
        $this->assign('status', ['0'=>'未处理', '1'=>'已处理']);
        return $this->fetch();
    }


}