<?php
/**
 * 平台设置
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-07-07
 * Time: 09:37
 */

namespace app\admin\controller;



class Site extends BaseController
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户注册协议编辑
     */
    public function register()
    {
        $reg = model('WebRegister')->find();
        if(request()->isAjax()){
            if($reg){
                $res = $reg->save(input('post.'));
            }else{
                $res = model('WebRegister')->save(input('post.'));
            }
            if($res){
                exit_json();
            }else{
                exit_json(-1, '保存失败');
            }
        }
        $this->assign('item', $reg['content']);
        return $this->fetch();
        
    }

    /**
     * 关于我们
     */
    public function about_us()
    {
        $reg = model('web_about_us')->find();
        if(request()->isAjax()){
            if($reg){
                $res = $reg->save(input('post.'));
            }else{
                $res = model('web_about_us')->save(input('post.'));
            }
            if($res){
                exit_json();
            }else{
                exit_json(-1, '保存失败');
            }
        }
        $this->assign('item', $reg['content']);
        return $this->fetch();

    }

    /**
     * 联系我们
     */
    public function contact_us()
    {
        $reg = model('web_contact_us')->find();
        if(request()->isAjax()){
            if($reg){
                $res = $reg->save(input('post.'));
            }else{
                $res = model('web_contact_us')->save(input('post.'));
            }
            if($res){
                exit_json();
            }else{
                exit_json(-1, '保存失败');
            }
        }
        $this->assign('telephone', $reg['telephone']);
        return $this->fetch();
    }


    /**
     * 首页轮播图设置
     */
    public function swiperList()
    {
        $list = model('swiper')->order('')->select();
        $this->assign('list', $list);
        return $this->fetch();

    }

    /**
     * 添加轮播图
     */
    public function swiperAdd()
    {
        if (request()->isAjax()) {
            $image = input('image');
            $ord = input('ord');
            $product_id = input('product_id');
            $res = model('swiper')->save(['image' => $image, 'ord' => $ord, 'product_id'=>$product_id]);
            if ($res) {
                exit_json();
            } else {
                exit_json(-1, '保存失败');
            }
        }
        return $this->fetch();
    }

    /**
     * 轮播编辑
     */
    public function swiperEdit()
    {
        $s_id = input('id');
        $swiper = model('swiper')->where('id', $s_id)->find();
        if (request()->isAjax()) {
            $res = $swiper->allowField(true)->save(input('post.'), ['id' => $s_id]);
            if ($res) {
                exit_json(1, '编辑成功');
            } else {
                exit_json(-1, '操作失败');
            }
        }

        $this->assign('item', $swiper);
        return $this->fetch();

    }

    /**
     * 删除轮播图
     */
    public function swiperDel()
    {
        $id = input('id');
        $res = model('swiper')->where('id', $id)->delete();
        if ($res) {
            exit_json();
        } else {
            exit_json(-1, '删除失败');
        }
    }

    /**
     * 搜索关键字设置
     */
    public function keywords()
    {
        $keywords = model("keywords")->find();
        if (request()->isAjax()) {
            $keywords1 = str_replace("，", ",", trim(input('keywords')));
            $count = count(explode(",", $keywords1));
            if ($count > config('recommendKey')) {
                exit_json(-1, '推荐搜索关键字最多' . config('recommendKey') . '个');
            }
            if($keywords){
                $keywords->save(['keywords' => $keywords1]);
            }else{
                model('keywords')->save(['keywords' => $keywords1]);
            }
            exit_json();
        } else {
            $this->assign('keystring', $keywords['keywords']);
            return $this->fetch();
        }
    }

    /**
     * 支付设置
     */
    public function paySet()
    {
        $item = db("bank_info")->find();
        if(request()->isAjax()){
            $data = input("post.");
            $data['update_time'] = time();
            if($item){
                $res = db("bank_info")->where("1=1")->update($data);
            }else{
                $res = db("bank_info")->insert($data);
            }
            if($res){
                exit_json();
            }else{
                exit_json(-1, '更新失败');
            }


        }else{
            $item = db("bank_info")->find();
            $this->assign("item", $item);
            return $this->fetch('paySet');
        }


    }



}