<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/1/22
 * Time: 16:45
 */

namespace app\common\model;


use think\Model;

class AgentLog extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
}