<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-09
 * Time: 11:47
 */

namespace app\common\model;


use think\Model;

class BuySupply extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}