<?php
/**
 *
 * 部门管理
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-10
 * Time: 10:55
 */

namespace app\common\model;


use think\Model;

class Department extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}