<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-07-10
 * Time: 15:22
 */

namespace app\common\model;


use think\Model;

class Employee extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
}