<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/4/23
 * Time: 21:50
 */

namespace app\common\model;


use think\Model;

class FollowOrder extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp=true;

}