<?php
/**
 * 商品规格
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.22
 * Time: 15:05
 */

namespace app\common\model;


use think\Model;

class GoodsProp extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

    /**
     * 获取规格库存
     * @param $good_id  商品id
     * @param $prop_id  规格id
     * @return int
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getCount($good_id, $prop_id)
    {
        $prop = $this->where(['good_id'=>$good_id, 'id'=>$prop_id])->find();
        return $prop['num'];
    }



}