<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-07-06
 * Time: 16:43
 */

namespace app\common\model;


use think\Model;

class JoinUs extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

}