<?php
/**
 * 搜索关键字
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.6.6
 * Time: 15:10
 */

namespace app\common\model;


use think\Model;

class Keywords extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = false;

}