<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/4/28
 * Time: 22:07
 */

namespace app\common\model;


use think\Model;

class LoginLogo extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}