<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/4/29
 * Time: 20:10
 */

namespace app\common\model;


use think\Model;

class News extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;

}