<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/4/29
 * Time: 20:11
 */

namespace app\common\model;


use think\Model;

class NewsCate extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}