<?php
/**
 * 申请退款订单
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-06-20
 * Time: 17:10
 */

namespace app\common\model;


use think\Model;

class OrderRefund extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}