<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2018/11/16
 * Time: 13:40
 */

namespace app\common\model;


use think\Model;

class OrderPre extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}