<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.6.2
 * Time: 16:05
 */

namespace app\common\model;


use think\Model;

class OrderDet extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
    protected $updateTime = false;


    public function getDetail($order_no)
    {
        $list =  $this->alias('a')->field('a.cost, a.num, a.cost*a.num total_money, a.good_name, a.prop_name, b.img image')->join('goods b', 'a.good_id=b.id')->where('order_no', $order_no)->select();
        $data = [];
        foreach ($list as $l){
            $temp = $l;
            $temp['image'] = explode(",", $l['image'])[0];
            $data[] = $temp;
        }
        return $data;
    }

}