<?php
/**
 * 支付订单
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.6.2
 * Time: 16:34
 */

namespace app\common\model;


use think\Model;

class PayOrder extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

}