<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-01
 * Time: 15:17
 */

namespace app\common\model;


use think\Model;

class ProductPropValue extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;


}