<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-01
 * Time: 15:21
 */

namespace app\common\model;


use think\Model;

class ProductAttr extends Model
{
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

    /**
     * 获取单个商品最低价
     * @param $product_id
     * @return array|false|\PDOStatement|string|Model
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getPropAttrOne($product_id)
    {
        $prop = $this->where('product_id', $product_id)->field('prop_value_name, price_one, price_comb')->order('price_comb')->find();
        return $prop;

    }
}