<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-01
 * Time: 15:18
 */

namespace app\common\model;


use think\Model;

class ProductPropName extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}