<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-07-30
 * Time: 10:42
 */

namespace app\common\model;


use think\Model;

class PropValue extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;


}