<?php
/**
 * 店铺公告
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-06-26
 * Time: 09:38
 */

namespace app\common\model;


use think\Model;

class Report extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}