<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.4.21
 * Time: 16:42
 */

namespace app\common\model;


use think\Model;

class ScoreSet extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}