<?php
/**
 * 用户积分日志
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.6.6
 * Time: 11:11
 */

namespace app\common\model;


use think\Model;

class ScoreLog extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
    protected $updateTime = false;




}