<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.14
 * Time: 11:39
 */

namespace app\common\model;


use think\Model;

class ShopDispatchArea extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }



}