<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/27
 * Time: 9:00
 */

namespace app\common\model;


use think\Model;

class SignLog extends Model
{
    protected $autoWriteTimestamp = true;
    protected $updateTime = false;
    protected $dateFormat = 'Y-m-d';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }


}