<?php
/**
 * 首页轮播图推荐
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.2
 * Time: 11:45
 */

namespace app\common\model;


use think\Model;

class Swiper extends Model
{
    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 根据店铺id获取轮播图信息
     * @param $shop_id
     * @return false|\PDOStatement|string|\think\Collection
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getSwiper($shop_id)
    {
        $res = $this->where('shop_id', 'eq', $shop_id)->order('ord desc')->select();
        if ($res) {
            return $res;
        } else {
            return $this->where('shop_id', 'eq', 0)->order('ord desc')->select();
        }
    }
}