<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/12
 * Time: 9:07
 */

namespace app\common\model;


use think\Model;

class SysConfig extends Model
{
    private $sysConfig;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->sysConfig = $this->where('status', 1)->column('value', 'key');
    }

    public function getSysConfig()
    {
        return $this->sysConfig;
    }

}