<?php
/**
 * Created by PhpStorm.
 * User: tsing
 * Date: 2019/4/29
 * Time: 15:53
 */

namespace app\common\model;


use think\Model;

class Tips extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

}