<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/23
 * Time: 11:58
 */

namespace app\common\model;


use app\admin\model\Coupon;
use think\Model;

class UserCoupon extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

    /**
     * 获取用户优惠券数量
     * @param $user_id
     * @return int|string
     */
    public function getCouponNum($user_id)
    {
        $num = $this->where('userid', 'eq', $user_id)->count();
        return $num;
    }

    /**
     * 赠送注册优惠券
     * @param $user_id
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function giveRegisterCoupon($user_id)
    {
        $couponModel = new Coupon();
        $couponList = $couponModel->where([
            'type' => 1,
            'start_time' => ['lt', date('Y-m-d H:i:s')],
            'end_time' => ['gt', date('Y-m-d H:i:s')]
        ])->select();
        $data = [];
        foreach ($couponList as $item) {
            $temp = [];
            $temp['couponId'] = $item['id'];
            $temp['userid'] = $user_id;
            $temp['name'] = $item['name'];
            $temp['cost'] = $item['cost'];
            $temp['start_time'] = $item['start_time'];
            $temp['min_cost'] = $item['min_cost'];
            $temp['end_time'] = $item['end_time'];
            $temp['type'] = $item['type'];
            $temp['shop_id'] = $item['shop_id'];
            $data[] = $temp;
        }
        $this->saveAll($data);
    }

}