<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.16
 * Time: 15:55
 */

namespace app\common\model;


use think\Model;

class UserCollection extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
    protected $updateTime = false;

}