<?php
/**
 * 用户实体类
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\1\24 0024
 * Time: 17:01
 */

namespace app\common\model;


use think\Model;

class User extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;

    /**
     * 根据用户id格式化单个用户
     * @param $user_id
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function formatOne($user_id)
    {
        $data = [];
        $user = $this->where('id', $user_id)->find();
        $data['user_id'] = $user['id'];
        $data['user_name'] = $user['user_name'];
        $data['head_img'] = __URL__.$user['head_img'];
        $data['telephone'] = $user['telephone'];
        $data['vip_code'] = $user['vip_code'];
        $data['open_id'] = $user['open_id'];
        return $data;
    }

    /**
     * 获取用户基本信息
     */
    public function getUserInfo($res)
    {

    }

    /**
     * 根据手机号和密码查询会员
     * @param $telephone
     * @param $password
     * @return array
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkUser($telephone, $password)
    {
    }

    /**
     * 根据手机号
     * @param $telephone
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkIsExist($telephone)
    {
    }

}