<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-08-10
 * Time: 15:41
 */

namespace app\common\model;


use think\Model;

class WebContactUs extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
}