<?php
/**
 * App用户通用类
 * Created by PhpStorm.
 * User: tsingStar
 * Date: 2018/1/19
 * Time: 8:50
 */

namespace app\app\controller;


use app\common\model\SendSms;
use app\common\model\User;
use think\Controller;

class Pub extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function getVersion()
    {
        $version = input('version');
        if ($version == config('version')) {
            exit_json(-1, '当前版本为最新版本');
        } else {
            exit_json(1, '有新版本', ['url' => config('download_url'), 'version' => config('version')]);
        }
    }

    /**
     *
     * 会员登陆
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    function login()
    {

        $telephone = input('telephone');
        $password = input('password');
        $userModel = new User();
        $user = $userModel->where('telephone', 'eq', $telephone)->find();
        if ($user) {
            if ($user['password'] != md5($password)) {
                exit_json(-1, '密码错误');
            }
            exit_json(1, '登陆成功', $userModel->formatOne($user['id']));
        } else {
            exit_json(-1, '会员不存在');
        }
    }

    /**
     * 验证码登陆
     */
    public function loginByCode()
    {
        $telephone = input('telephone');
        $code = input('code');
        $vcode = model('SmsLog')->where(['create_time' => ['gt', time() - 30], 'status' => 0, 'telephone' => $telephone, 'type' => 3])->value('code');
        if ($code != $vcode) {
            exit_json(-1, '验证码错误');
        }
        $userModel = new User();
        $user = $userModel->where('telephone', $telephone)->find();
        if ($user) {
            exit_json(1, '登陆成功', $userModel->formatOne($user['id']));
        }
    }

    /**
     * 会员注册
     */
    function register()
    {
        $telephone = input('telephone');
        $password = input('password');
        $vcode = input('code');
        $vip_code = input('vip_code');
        $user = model('user')->where('telephone', $telephone)->find();
        if ($user) {
            exit_json(-1, '手机号已注册');
        } else {

            $sms = model('SmsLog')->where(['create_time' => ['gt', time() - 30], 'status' => 0, 'telephone' => $telephone, 'type' => 1])->find();
            if ($sms['code'] != $vcode) {
                exit_json(-1, '验证码错误');
            }
            $res = model('user')->isUpdate(false)->save(['telephone' => $telephone, 'password' => md5($password), 'vip_code' => $vip_code, 'user_name'=>uniqid()]);
            if ($res) {
                $sms->save(['status' => 1]);
                $user_id = model('user')->getAttr('id');
                exit_json(1, '注册成功', model('user')->formatOne($user_id));
            } else {
                exit_json(-1, '注册失败');
            }
        }
    }

    /**
     * 重置密码
     */
    function resetPassword()
    {
        $data = input('post.');
        if (!$data['telephone'] || !$data['code'] || !$data['password']) {
            exit_json(-1, '参数错误');
        }
        $code = model('SmsLog')->where([ 'status' => 0, 'telephone' => $data['telephone'], 'type' => 2])->value('code');
        if ($code != $data['code']) {
            exit_json(-1, '验证码错误');
        }
        $userModel = new User();
        $user = $userModel->where(['telephone' => $data['telephone']])->find();
        $res = $user->save(['password' => md5($data['password'])]);
        if ($res) {
            exit_json(1, '重置密码成功');
        } else {
            exit_json(-1, '重置密码失败');
        }
    }

    /**
     * 获取验证码
     */
    function getVcode()
    {
        //sendType  1 注册 2 忘记密码 3 短信验证码登陆
        $telephone = input('telephone');
        $sendType = input('sendType');
        if (!test_tel($telephone)) {
            exit_json(-1, '手机号不合法');
        }
        $user = model('user')->where('telephone', $telephone)->find();
        switch ($sendType) {
            case 1:
                if ($user) {
                    exit_json(-1, '手机号已注册过');
                }
                break;
            case 2:
                if (!$user) {
                    exit_json(-1, '手机号未注册过');
                }
                break;
            case 3:
                if (!$user) {
                    exit_json(-1, '手机号未注册，请注册后登陆');
                }
                break;
            default:
                exit_json(-1, '参数错误');
        }
        $code = rand(100000, 999999);
        $remain_time = '30秒';
        $content = urlencode("$code##$remain_time");
        $sendSms = new SendSms($telephone, config('sms.tempId'), $content);
        $res = $sendSms->sendVcode();
        if ($res) {
            model('SmsLog')->save(['telephone' => $telephone, 'type' => $sendType, 'code' => $code]);
            exit_json(1, '验证码发送成功');
        } else {
            exit_json(-1, $sendSms->getError());
        }
    }

}