<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.22
 * Time: 11:36
 */

namespace app\app\model;


use think\Model;

class Shopcart extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected $autoWriteTimestamp = true;
    protected $updateTime = false;



}