<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.23
 * Time: 17:36
 */

namespace app\app\model;


use think\Model;

class UserAddress extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}